# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-01 06:52
from __future__ import unicode_literals

import SenderNeClientAPI.Commons.RandomIds
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SenderNeClientAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrivateStoreInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('db_name', models.CharField(default=SenderNeClientAPI.Commons.RandomIds.get_random_PrivateUserStore_dbName, max_length=100, null=True)),
                ('store_name', models.CharField(default=SenderNeClientAPI.Commons.RandomIds.get_random_PrivateUserStore_storeName, max_length=100, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='related_user_private_store_info', to=settings.AUTH_USER_MODEL, verbose_name='store owner')),
            ],
            options={
                'db_table': 'at_user_private_store_infos',
            },
        ),
    ]
