# Generated by Django 2.0.8 on 2018-11-28 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SenderNeClientAPI', '0004_auto_20181104_0034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
        migrations.RemoveField(
            model_name='userprivatestoreinfo',
            name='owner',
        ),
        migrations.DeleteModel(
            name='UserPrivateStoreInfo',
        ),
    ]
